import type { DiagramSpec } from "../engine/types";
import { E15_NOTE } from "./c5-shared";

const SRC = "KB §5.5 (Figure 11.3 arrow map) · Slide C5 p.21";

/**
 * D5.5 — Figure 11.3 "Documentary Letter of Credit" (slide C5 p.21): Carrier on top, U.S. seller (New York)
 * left and Canadian buyer (Montreal) right, Advising/confirming bank bottom-left, Issuing bank bottom-right.
 * The figure has numbered arrows but no step text — meanings follow the KB `derived-order` map (amendment A3).
 */
const spec: DiagramSpec = {
  id: "c5-lc-fig113",
  chapter: "C5",
  title: "Figure 11.3 – Documentary Letter of Credit",
  titleVi: "Thư tín dụng theo Figure 11.3 – 11 bước (có người chuyên chở)",
  provenance: "slide",
  slideRef: "C5 p.21",
  note: "Thứ tự diễn giải từ các mũi tên của Figure 11.3 (hình chỉ có số, không có chữ). Mũi tên (5) trên slide không có đầu mũi tên; hướng Seller → Carrier theo diễn giải trong KB.",
  nodes: [
    {
      id: "carrier",
      label: "Carrier",
      labelVi: "Người chuyên chở",
      role: "carrier",
      x: 500,
      y: 70,
      w: 250,
      h: 84,
      shape: "rect",
      descVi: "Người chuyên chở nhận hàng từ người bán (cấp B/L) và chỉ giao hàng cho người xuất trình B/L – vì vậy B/L là chứng từ sở hữu hàng hóa.",
      links: [{ label: "C7 · Chức năng của B/L", to: "/learn/c7#bl-functions" }],
    },
    {
      id: "seller",
      label: "U.S. seller\nin New York",
      labelVi: "Người bán – Beneficiary",
      role: "seller",
      x: 200,
      y: 270,
      w: 250,
      h: 100,
      shape: "rect",
      aka: ["Beneficiary"],
      descVi: "Người bán: ký hợp đồng thanh toán bằng L/C, giao hàng cho người chuyên chở, xuất trình chứng từ cho ngân hàng thông báo/xác nhận và được trả tiền.",
    },
    {
      id: "buyer",
      label: "Canadian buyer\nin Montreal",
      labelVi: "Người mua – Applicant",
      role: "buyer",
      x: 800,
      y: 270,
      w: 250,
      h: 100,
      shape: "rect",
      aka: ["Applicant"],
      descVi: "Người mua: yêu cầu mở L/C, nhận chứng từ từ ngân hàng phát hành, xuất trình B/L cho người chuyên chở để nhận hàng và trả tiền cho ngân hàng.",
    },
    {
      id: "advising",
      label: "Advising/confirming\nbank in New York",
      labelVi: "Ngân hàng thông báo/xác nhận",
      role: "sellerBank",
      x: 200,
      y: 515,
      w: 290,
      h: 100,
      shape: "rect",
      aka: ["Advising bank", "Confirming bank"],
      descVi: "Ngân hàng ở nước người bán: thông báo (xác nhận) L/C, nhận chứng từ và trả tiền cho người bán, chuyển chứng từ cho ngân hàng phát hành và được hoàn trả.",
    },
    {
      id: "issuing",
      label: "Issuing bank\nin Montreal",
      labelVi: "Ngân hàng phát hành",
      role: "buyerBank",
      x: 800,
      y: 515,
      w: 250,
      h: 100,
      shape: "rect",
      aka: ["Issuing bank", "Opening bank"],
      descVi: "Ngân hàng của người mua: phát hành L/C, nhận chứng từ, hoàn trả cho ngân hàng bên bán, giao chứng từ cho người mua và thu tiền người mua.",
    },
  ],
  edges: [
    { id: "f1", from: "seller", to: "buyer", kind: "info", both: true },
    { id: "f2", from: "buyer", to: "issuing", kind: "info", curve: 46 },
    { id: "f3", from: "issuing", to: "advising", kind: "info", curve: 30 },
    { id: "f4", from: "advising", to: "seller", kind: "info", curve: -32 },
    { id: "f5", from: "seller", to: "carrier", kind: "goods" },
    { id: "f6", from: "seller", to: "advising", kind: "document", both: true, curve: -32 },
    { id: "f7", from: "advising", to: "issuing", kind: "document" },
    { id: "f8", from: "issuing", to: "advising", kind: "money", curve: -30 },
    { id: "f9", from: "issuing", to: "buyer", kind: "document" },
    { id: "f10", from: "buyer", to: "carrier", kind: "document" },
    { id: "f11", from: "buyer", to: "issuing", kind: "money", curve: -46 },
  ],
  steps: [
    {
      id: "s1",
      order: 1,
      title: "Sales contract with L/C payment",
      titleVi: "Người bán và người mua ký hợp đồng, thanh toán bằng L/C",
      edgeIds: ["f1"],
      actors: ["seller", "buyer"],
      what: "Mũi tên hai chiều giữa người bán và người mua: hai bên thỏa thuận hợp đồng mua bán với điều khoản thanh toán bằng L/C.",
      why: "Điều khoản thanh toán trong hợp đồng là cơ sở để người mua mở L/C ở bước 2. Sơ đồ 9 bước không vẽ bước này.",
      source: SRC,
      practiceTopic: "lc-procedure",
      links: [{ label: "C6 · Điều khoản thanh toán", to: "/learn/c6#art-payment" }],
    },
    {
      id: "s2",
      order: 2,
      title: "Buyer applies for the L/C",
      titleVi: "Người mua yêu cầu ngân hàng phát hành mở L/C",
      edgeIds: ["f2"],
      actors: ["buyer", "issuing"],
      what: "Người mua (applicant) làm đơn yêu cầu ngân hàng phát hành ở Montreal mở L/C.",
      why: "Tương ứng bước 1 của sơ đồ 9 bước: L/C do người mua mở tại ngân hàng của mình.",
      trap: "L/C do người MUA mở, không phải người bán.",
      source: SRC,
      practiceTopic: "lc-parties",
    },
    {
      id: "s3",
      order: 3,
      title: "Issuing bank sends the L/C to the advising/confirming bank",
      titleVi: "Ngân hàng phát hành gửi L/C cho ngân hàng thông báo/xác nhận",
      edgeIds: ["f3"],
      actors: ["issuing", "advising"],
      what: "Ngân hàng phát hành gửi L/C sang ngân hàng thông báo/xác nhận ở New York.",
      why: "Tương ứng bước 2 của sơ đồ 9 bước.",
      documents: ["Letter of credit (L/C)"],
      source: SRC,
      practiceTopic: "lc-procedure",
    },
    {
      id: "s4",
      order: 4,
      title: "Advising/confirming bank advises (confirms) the L/C to the seller",
      titleVi: "Ngân hàng thông báo/xác nhận báo (xác nhận) L/C cho người bán",
      edgeIds: ["f4"],
      actors: ["advising", "seller"],
      what: "Ngân hàng ở New York thông báo L/C cho người bán; nếu là ngân hàng xác nhận thì đồng thời xác nhận L/C.",
      why: "Tương ứng bước 3 của sơ đồ 9 bước. Người bán kiểm tra L/C trước khi giao hàng.",
      trap: "Advising bank (chỉ thông báo) ≠ confirming bank (thêm cam kết thanh toán của chính mình).",
      source: SRC,
      practiceTopic: "lc-checklist",
    },
    {
      id: "s5",
      order: 5,
      title: "Seller ships goods to the carrier and receives the B/L",
      titleVi: "Người bán giao hàng cho người chuyên chở, nhận vận đơn (B/L)",
      edgeIds: ["f5"],
      actors: ["seller", "carrier"],
      what: "Người bán giao hàng cho người chuyên chở và nhận vận đơn (B/L) – một trong các chứng từ L/C yêu cầu.",
      why: "Tương ứng bước 4 (Goods) của sơ đồ 9 bước, nhưng ở đây hàng đi đến NGƯỜI CHUYÊN CHỞ chứ không thẳng đến người mua.",
      documents: ["Bill of lading (B/L)"],
      source: SRC,
      practiceTopic: "bl-functions",
    },
    {
      id: "s6",
      order: 6,
      title: "Seller presents documents and gets paid",
      titleVi: "Người bán xuất trình chứng từ và được trả tiền",
      edgeIds: ["f6"],
      actors: ["seller", "advising"],
      what: "Mũi tên hai chiều: người bán xuất trình bộ chứng từ (có B/L) cho ngân hàng thông báo/xác nhận và được trả tiền.",
      why: "Gộp bước 5 và bước 9 của sơ đồ 9 bước. Chứng từ phải xuất trình không muộn hơn 21 ngày sau ngày giao hàng và trong thời hạn hiệu lực của L/C.",
      ext: E15_NOTE,
      source: SRC,
      practiceTopic: "lc-dates",
      links: [{ label: "Công cụ kiểm tra ngày L/C", to: "/tools/lc-dates" }],
    },
    {
      id: "s7",
      order: 7,
      title: "Advising/confirming bank forwards documents to the issuing bank",
      titleVi: "Ngân hàng thông báo/xác nhận chuyển chứng từ cho ngân hàng phát hành",
      edgeIds: ["f7"],
      actors: ["advising", "issuing"],
      what: "Ngân hàng ở New York chuyển bộ chứng từ sang ngân hàng phát hành ở Montreal.",
      why: "Tương ứng bước 6 của sơ đồ 9 bước. Ngân hàng chỉ xét chứng từ, không liên quan đến hàng hóa.",
      source: SRC,
      practiceTopic: "discrepancies",
    },
    {
      id: "s8",
      order: 8,
      title: "Issuing bank reimburses the advising/confirming bank",
      titleVi: "Ngân hàng phát hành hoàn trả tiền cho ngân hàng thông báo/xác nhận",
      edgeIds: ["f8"],
      actors: ["issuing", "advising"],
      what: "Ngân hàng phát hành kiểm tra chứng từ, chấp nhận và hoàn trả tiền cho ngân hàng bên bán.",
      why: "Tương ứng bước 7 của sơ đồ 9 bước: cam kết trả tiền của ngân hàng phát hành được thực hiện.",
      source: SRC,
      practiceTopic: "lc-concept",
    },
    {
      id: "s9",
      order: 9,
      title: "Issuing bank releases the documents to the buyer",
      titleVi: "Ngân hàng phát hành giao chứng từ cho người mua",
      edgeIds: ["f9"],
      actors: ["issuing", "buyer"],
      what: "Ngân hàng phát hành giao bộ chứng từ (có B/L) cho người mua.",
      why: "Tương ứng nửa đầu bước 8 của sơ đồ 9 bước. Không có B/L, người mua không nhận được hàng ở bước 10.",
      documents: ["Bill of lading (B/L)"],
      source: SRC,
      practiceTopic: "lc-procedure",
    },
    {
      id: "s10",
      order: 10,
      title: "Buyer presents the B/L to the carrier and collects the goods",
      titleVi: "Người mua xuất trình B/L cho người chuyên chở để nhận hàng",
      edgeIds: ["f10"],
      actors: ["buyer", "carrier"],
      what: "Người mua xuất trình B/L cho người chuyên chở; người chuyên chở giao hàng cho người cầm B/L.",
      why: "Người chuyên chở chỉ giao hàng khi có B/L → B/L là CHỨNG TỪ SỞ HỮU hàng hóa (document of title). Sơ đồ 9 bước không vẽ bước này.",
      trap: "Người mua nhận hàng nhờ xuất trình B/L, không phải nhờ L/C.",
      documents: ["Bill of lading (B/L)"],
      source: SRC,
      practiceTopic: "bl-functions",
      links: [{ label: "C7 · 3 chức năng của B/L", to: "/learn/c7#bl-functions" }],
    },
    {
      id: "s11",
      order: 11,
      title: "Buyer pays the issuing bank (account debited)",
      titleVi: "Người mua trả tiền cho ngân hàng phát hành (hoặc bị ghi nợ)",
      edgeIds: ["f11"],
      actors: ["buyer", "issuing"],
      what: "Người mua trả tiền cho ngân hàng phát hành hoặc bị ghi nợ tài khoản.",
      why: "Tương ứng nửa sau bước 8 của sơ đồ 9 bước: ngân hàng phát hành thu lại khoản đã trả thay người mua.",
      source: SRC,
      practiceTopic: "lc-procedure",
    },
  ],
  keyTakeaways: [
    "Figure 11.3 thêm NGƯỜI CHUYÊN CHỞ: người bán giao hàng cho người chuyên chở (5), người mua xuất trình B/L để nhận hàng (10).",
    "Người chuyên chở chỉ giao hàng cho người cầm B/L → B/L là chứng từ sở hữu hàng hóa.",
    "Ngân hàng chỉ xử lý chứng từ và tiền; hàng đi qua người chuyên chở.",
    "So với sơ đồ 9 bước: thêm (1) hợp đồng và (10) xuất trình B/L; (6) gộp xuất trình chứng từ + nhận tiền.",
  ],
  quiz: { order: true, actor: true, gap: true },
};

export default spec;

/** Derived mapping between the 9-step flow (C5 p.20) and Figure 11.3 (C5 p.21), from the KB arrow maps. */
export const FIG113_MAPPING: { nine: string; fig: string; noteVi: string }[] = [
  { nine: "—", fig: "1", noteVi: "Hợp đồng mua bán thanh toán bằng L/C (chỉ có trên Figure 11.3)" },
  { nine: "1", fig: "2", noteVi: "Người mua yêu cầu mở L/C" },
  { nine: "2", fig: "3", noteVi: "Ngân hàng phát hành gửi L/C cho ngân hàng bên bán" },
  { nine: "3", fig: "4", noteVi: "Thông báo (xác nhận) L/C cho người bán" },
  { nine: "4 (Goods)", fig: "5", noteVi: "Giao hàng – Figure 11.3: giao cho người chuyên chở" },
  { nine: "5 + 9", fig: "6", noteVi: "Xuất trình chứng từ ⇄ được trả tiền (mũi tên hai chiều)" },
  { nine: "6", fig: "7", noteVi: "Chuyển chứng từ sang ngân hàng phát hành" },
  { nine: "7", fig: "8", noteVi: "Ngân hàng phát hành trả/hoàn trả cho ngân hàng bên bán" },
  { nine: "8", fig: "9 + 11", noteVi: "Giao chứng từ cho người mua; người mua trả tiền / bị ghi nợ" },
  { nine: "—", fig: "10", noteVi: "Người mua xuất trình B/L cho người chuyên chở để nhận hàng (chỉ có trên Figure 11.3)" },
];
