import type { DiagramSpec } from "../engine/types";
import { DISCREPANCIES, E15_NOTE, LC_CHECKLIST, LC_CONTENTS, LC_EXAMPLE_DOCUMENTS } from "./c5-shared";

const SRC = "KB §5.5 · Slide C5 p.20";

/**
 * D5.4 — "Documentary credit procedures" (slide C5 p.20). Layout as on the slide: Advising bank top-left,
 * Issuing bank top-right, Exporter bottom-left, Importer bottom-right. Between the banks the slide stacks
 * (7) on top, (6) in the middle, (2) at the bottom; on the exporter side (9) left, (5) middle, (3) right.
 */
const spec: DiagramSpec = {
  id: "c5-lc-basic",
  chapter: "C5",
  title: "Documentary credit procedures",
  titleVi: "Quy trình thư tín dụng (L/C) – 9 bước",
  provenance: "slide",
  slideRef: "C5 p.20",
  nodes: [
    {
      id: "advising",
      label: "ADVISING BANK",
      labelVi: "Ngân hàng thông báo",
      role: "sellerBank",
      x: 250,
      y: 140,
      w: 310,
      h: 130,
      shape: "ellipse",
      aka: ["Advising bank", "Confirming bank / Paying bank (khi được chỉ định)", "Ngân hàng của người thụ hưởng (beneficiary's bank)"],
      descVi: "Ngân hàng bên người bán: thông báo L/C cho người bán, nhận bộ chứng từ của người bán và chuyển cho ngân hàng phát hành; theo slide, trả tiền cho người bán ở bước 9.",
      links: [{ label: "C5 · Các bên trong L/C", to: "/learn/c5#lc-concept" }],
    },
    {
      id: "issuing",
      label: "ISSUING BANK",
      labelVi: "Ngân hàng phát hành",
      role: "buyerBank",
      x: 750,
      y: 140,
      w: 310,
      h: 130,
      shape: "ellipse",
      aka: ["Issuing bank", "Opening bank (ngân hàng mở L/C)", "Ngân hàng của người yêu cầu (applicant's bank)"],
      descVi: "Ngân hàng bên người mua: phát hành L/C theo yêu cầu của người mua, kiểm tra chứng từ, thanh toán và giao chứng từ cho người mua. Cam kết thanh toán của ngân hàng là cốt lõi của L/C.",
      links: [
        { label: "C5 · Khái niệm L/C", to: "/learn/c5#lc-concept" },
        { label: "C5 · Nội dung L/C (13 mục)", to: "/learn/c5#lc-contents" },
      ],
    },
    {
      id: "exporter",
      label: "EXPORTER",
      labelVi: "Người bán – Beneficiary",
      role: "seller",
      x: 250,
      y: 480,
      w: 310,
      h: 130,
      shape: "ellipse",
      aka: ["Seller", "Beneficiary (người thụ hưởng)"],
      descVi: "Người bán: kiểm tra L/C, giao hàng khi điều kiện L/C đã đáp ứng, lập và xuất trình đúng bộ chứng từ L/C yêu cầu để được thanh toán.",
      links: [
        { label: "C5 · Checklist L/C của nhà xuất khẩu", to: "/learn/c5#lc-checklist" },
        { label: "C8 · Quy trình xuất khẩu", to: "/learn/c8#export-procedure" },
      ],
    },
    {
      id: "importer",
      label: "IMPORTER",
      labelVi: "Người mua – Applicant",
      role: "buyer",
      x: 750,
      y: 480,
      w: 310,
      h: 130,
      shape: "ellipse",
      aka: ["Buyer", "Applicant (người yêu cầu mở L/C)"],
      descVi: "Người mua: làm đơn mở L/C tại ngân hàng của mình, nhận bộ chứng từ từ ngân hàng phát hành và trả tiền (hoặc bị ghi nợ tài khoản).",
      links: [{ label: "C8 · Quy trình nhập khẩu (mở L/C)", to: "/learn/c8#import-procedure" }],
    },
  ],
  edges: [
    { id: "e1", from: "importer", to: "issuing", kind: "info", curve: -45 },
    { id: "e2", from: "issuing", to: "advising", kind: "info", curve: -38 },
    { id: "e3", from: "advising", to: "exporter", kind: "info", curve: -62 },
    { id: "e4", from: "exporter", to: "importer", kind: "goods", label: "Goods" },
    { id: "e5", from: "exporter", to: "advising", kind: "document" },
    { id: "e6", from: "advising", to: "issuing", kind: "document" },
    { id: "e7", from: "issuing", to: "advising", kind: "money", curve: 38 },
    { id: "e8", from: "issuing", to: "importer", kind: "document", curve: -45 },
    { id: "e9", from: "advising", to: "exporter", kind: "money", curve: 62 },
  ],
  steps: [
    {
      id: "s1",
      order: 1,
      title: "Buyer applies for and opens the L/C with the issuing bank",
      titleVi: "Người mua làm đơn và mở L/C tại ngân hàng phát hành",
      edgeIds: ["e1"],
      actors: ["importer", "issuing"],
      what: "Người mua (applicant) làm đơn đề nghị mở L/C tại ngân hàng của mình – ngân hàng phát hành (issuing/opening bank). Nội dung L/C phải khớp với điều khoản thanh toán trong hợp đồng.",
      why: "L/C là cam kết trả tiền của ngân hàng thay cho người mua, với điều kiện người bán đáp ứng các điều kiện của L/C. Từ đây người bán dựa vào cam kết của ngân hàng chứ không chỉ vào uy tín của người mua.",
      trap: "L/C do người MUA mở tại ngân hàng của người mua (ngân hàng phát hành), không phải do người bán mở.",
      source: SRC,
      practiceTopic: "lc-procedure",
      links: [{ label: "C8 · Bước 2 nhập khẩu: mở L/C", to: "/learn/c8#import-procedure" }],
    },
    {
      id: "s2",
      order: 2,
      title: "Issuing bank issues the L/C, forwarding it to the advising bank",
      titleVi: "Ngân hàng phát hành phát hành L/C, chuyển cho ngân hàng thông báo",
      edgeIds: ["e2"],
      actors: ["issuing", "advising"],
      what: "Ngân hàng phát hành phát hành L/C và chuyển L/C sang ngân hàng thông báo (advising bank) ở nước người bán.",
      why: "L/C đi qua ngân hàng ở nước người bán để đến tay người bán; nội dung L/C (13 mục) xác định chính xác người bán phải làm gì để được trả tiền.",
      documents: ["Letter of credit (L/C)"],
      trap: "L/C được chuyển từ ngân hàng sang ngân hàng (issuing → advising), không gửi thẳng từ ngân hàng phát hành cho người bán.",
      details: [{ title: "Nội dung của L/C", items: LC_CONTENTS }],
      source: SRC,
      practiceTopic: "lc-contents",
    },
    {
      id: "s3",
      order: 3,
      title: "Advising bank notifies the seller of the L/C",
      titleVi: "Ngân hàng thông báo báo L/C cho người bán",
      edgeIds: ["e3"],
      actors: ["advising", "exporter"],
      what: "Ngân hàng thông báo báo cho người bán (beneficiary) về L/C. Người bán kiểm tra L/C theo checklist trước khi chuẩn bị giao hàng.",
      why: "Mọi điều kiện L/C không thực hiện được (tên, số tiền, ngày, chứng từ…) cần được phát hiện NGAY, trước khi giao hàng — nếu không, chứng từ sẽ có bất hợp lệ.",
      trap: "Nếu L/C không khớp hợp đồng, người bán yêu cầu tu chỉnh L/C (amendment) TRƯỚC khi giao hàng; sai biệt lớn (major) chỉ sửa được bằng tu chỉnh.",
      details: [{ title: "Checklist L/C của nhà xuất khẩu", items: LC_CHECKLIST, checklist: true }],
      source: SRC,
      practiceTopic: "lc-checklist",
      links: [{ label: "C8 · Bước 2 xuất khẩu: kiểm tra L/C", to: "/learn/c8#export-procedure" }],
    },
    {
      id: "s4",
      order: 4,
      title: "Seller delivers the goods once the terms of the L/C have been met",
      titleVi: "Người bán giao hàng khi điều kiện L/C đã được đáp ứng",
      edgeIds: ["e4"],
      actors: ["exporter", "importer"],
      what: "Người bán giao hàng cho người mua (thông qua người chuyên chở) khi các điều kiện của L/C đã được đáp ứng. Ngày giao hàng phải nằm trong thời hạn hiệu lực của L/C (sau ngày phát hành, trước ngày hết hạn).",
      why: "Hàng đi thẳng từ người bán sang người mua; ngân hàng không nhận hay kiểm tra hàng. Đây là mũi tên hàng hóa duy nhất trong sơ đồ.",
      trap: "Ngân hàng không liên quan đến hàng hóa (banks have nothing to do with the goods) — ngân hàng chỉ xét chứng từ.",
      source: SRC,
      practiceTopic: "lc-dates",
      links: [{ label: "Công cụ: kiểm tra ngày L/C", to: "/tools/lc-dates" }],
    },
    {
      id: "s5",
      order: 5,
      title: "Seller forwards the documents stipulated in the L/C to the advising bank",
      titleVi: "Người bán xuất trình bộ chứng từ theo L/C cho ngân hàng thông báo",
      edgeIds: ["e5"],
      actors: ["exporter", "advising"],
      what: "Sau khi giao hàng, người bán lập bộ chứng từ đúng như L/C quy định và xuất trình cho ngân hàng thông báo. Chứng từ phải xuất trình không muộn hơn 21 ngày sau ngày giao hàng VÀ trong thời hạn hiệu lực của L/C.",
      why: "Chứng từ là trọng tâm của giao dịch L/C (documents are the key issue): người bán được trả tiền khi xuất trình chứng từ phù hợp, đúng hạn.",
      documents: LC_EXAMPLE_DOCUMENTS,
      trap: "Hai giới hạn cùng áp dụng: 21 ngày sau ngày giao hàng và trước ngày hết hạn L/C — mốc nào đến trước thì phải tuân theo mốc đó.",
      source: `${SRC} · KB §5.5 – Remarks on dates`,
      practiceTopic: "lc-dates",
      links: [{ label: "Công cụ: kiểm tra ngày L/C", to: "/tools/lc-dates" }],
    },
    {
      id: "s6",
      order: 6,
      title: "Advising bank forwards the documents to the issuing bank for review",
      titleVi: "Ngân hàng thông báo chuyển chứng từ cho ngân hàng phát hành kiểm tra",
      edgeIds: ["e6"],
      actors: ["advising", "issuing"],
      what: "Ngân hàng thông báo chuyển bộ chứng từ của người bán sang ngân hàng phát hành để kiểm tra (review) đối chiếu với điều kiện L/C.",
      why: "Ngân hàng phát hành chỉ trả tiền cho chứng từ phù hợp; chứng từ có bất hợp lệ (discrepancy) thì phải được khắc phục tùy loại.",
      documents: LC_EXAMPLE_DOCUMENTS,
      details: [{ title: "Ba loại bất hợp lệ chứng từ (discrepancies)", items: DISCREPANCIES }],
      source: SRC,
      practiceTopic: "discrepancies",
    },
    {
      id: "s7",
      order: 7,
      title: "Issuing bank reviews, accepts and pays the seller's bank (advising bank)",
      titleVi: "Ngân hàng phát hành kiểm tra, chấp nhận và thanh toán cho ngân hàng bên bán",
      edgeIds: ["e7"],
      actors: ["issuing", "advising"],
      what: "Khi chứng từ phù hợp, ngân hàng phát hành chấp nhận và thanh toán cho ngân hàng của người bán (ngân hàng thông báo).",
      why: "Đây là lúc cam kết thanh toán của ngân hàng được thực hiện — dựa trên chứng từ, không dựa vào việc hàng đã đến hay chất lượng hàng ra sao.",
      details: [{ title: "Ba loại bất hợp lệ chứng từ (discrepancies)", items: DISCREPANCIES }],
      trap: "Ngân hàng trả tiền vì chứng từ phù hợp, không phải vì người mua đã nhận được hàng.",
      source: SRC,
      practiceTopic: "lc-concept",
    },
    {
      id: "s8",
      order: 8,
      title: "Issuing bank forwards the documents to the buyer; the buyer pays or the buyer's account is debited",
      titleVi: "Ngân hàng phát hành giao chứng từ cho người mua; người mua trả tiền hoặc bị ghi nợ",
      edgeIds: ["e8"],
      actors: ["issuing", "importer"],
      what: "Ngân hàng phát hành giao bộ chứng từ cho người mua; người mua trả tiền cho ngân hàng hoặc bị ghi nợ tài khoản.",
      why: "Người mua cần chứng từ — nhất là vận đơn (B/L), chứng từ sở hữu hàng hóa — để nhận hàng từ người chuyên chở.",
      documents: ["Bill of Lading", "Commercial Invoice", "Packing List"],
      source: `${SRC} · KB §7.5`,
      practiceTopic: "lc-procedure",
      links: [{ label: "Xem Figure 11.3 (có người chuyên chở)", to: "/diagrams/c5-lc-fig113" }],
    },
    {
      id: "s9",
      order: 9,
      title: "Advising bank pays the seller as specified in the L/C",
      titleVi: "Ngân hàng thông báo trả tiền cho người bán theo quy định của L/C",
      edgeIds: ["e9"],
      actors: ["advising", "exporter"],
      what: "Ngân hàng của người bán trả tiền cho người bán theo quy định của L/C — kết thúc dòng tiền.",
      why: "Người bán nhận tiền từ ngân hàng sau khi đã giao hàng và xuất trình chứng từ phù hợp; rủi ro không được thanh toán do người mua được thay bằng cam kết của ngân hàng.",
      trap: "Ngân hàng thông báo (advising) khác ngân hàng xác nhận (confirming): chỉ thông báo L/C thì chưa phải là cam kết trả tiền.",
      ext: E15_NOTE,
      source: `${SRC} · ERRATA E-15`,
      practiceTopic: "lc-parties",
    },
  ],
  keyTakeaways: [
    "Ngân hàng giao dịch trên CHỨNG TỪ, không liên quan đến hàng hóa (documents, not goods).",
    "L/C là cam kết trả tiền của ngân hàng thay cho người mua → người bán dựa vào cam kết của ngân hàng thay vì tín dụng của người mua.",
    "Trình tự: mở và thông báo L/C (1–3) → giao hàng (4) → chứng từ đi (5–6) → tiền về (7, 9), chứng từ đến người mua (8).",
    "Xuất trình chứng từ không muộn hơn 21 ngày sau ngày giao hàng và trong thời hạn hiệu lực của L/C.",
  ],
  quiz: { order: true, actor: true, gap: true },
};

export default spec;
